name: 'Surefire Report'
description: 'Generates a test report'
inputs:
  report_paths:
    description: "Glob expression to surefire or failsafe report paths."
    required: false
    default: "**/surefire-reports/TEST-*.xml"
  skip_publishing:
    description: "Whether to publish test results as annotation or not"
    required: false
    default: "true"
  check_name:
    description: "Check name to use when creating a check run"
    required: false
    default: "Test Report"
  commit:
    description: "The commit sha to update the status"
    required: false
    
runs:
  using: "composite"
  steps: 
    - name: Check Surefire Report
      uses: ScaCap/action-surefire-report@v1.1.0
      with:
        fail_on_test_failures: true
        fail_if_no_tests: false
        create_check: false
        skip_publishing: ${{ inputs.skip_publishing }}
        report_paths: ${{ inputs.report_paths }}
        commit: ${{ inputs.commit }}
        check_name: ${{ inputs.check_name }}
      env:
        # https://github.com/ScaCap/action-surefire-report/issues/17
        NODE_OPTIONS: '--max_old_space_size=4096'
