name: 'Surefire Report'
description: 'Generates a test report'
inputs:
  report_paths:
    description: "Glob expression to surefire or failsafe report paths."
    required: false
    default: "**/surefire-reports/TEST-*.xml"

runs:
  using: "composite"
  steps: 
    - name: Check Surefire Report
      uses: ScaCap/action-surefire-report@v1.0.13
      with:
        fail_on_test_failures: true
        fail_if_no_tests: false
        skip_publishing: true
        report_paths: ${{ inputs.report_paths }}
      env:
        # https://github.com/ScaCap/action-surefire-report/issues/17
        NODE_OPTIONS: '--max_old_space_size=4096'
