name: 'Java + Maven configuration'
description: 'Java and Maven version setup'
inputs:
  java-version:
    description: "the java version"
    default: "11"
    required: false
  maven-version:
    description: "the maven version"
    default: "3.8.6"
    required: false
  cache-key-prefix:
    description: "the cache key"
    required: false
  allow-snapshots:
    description: "the cache key"
    required: false
    default: "false"

runs:
  using: "composite"
  steps:
    - name: Setup Jdk
      uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: ${{ inputs.java-version }}
        check-latest: true
    - name: Set up Maven
      uses: stCarolas/setup-maven@v4.2
      with:
        maven-version: ${{ inputs.maven-version }}
    - name: Cache Maven packages
      uses: actions/cache@v2
      with:
        path:  ~/.m2
        key: ${{ inputs.cache-key-prefix }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys:  ${{ inputs.cache-key-prefix }}-m2
    - name: Setup Maven Settings
      uses: whelk-io/maven-settings-xml-action@v20
      with:
        repositories: >
          [
            {
              "id": "jboss-public-repository-group",
              "name": "JBoss Public Repository Group",
              "url": "https://repository.jboss.org/nexus/content/groups/public",
              "releases": {
                "enabled": "true",
                "updatePolicy": "never"
              },
              "snapshots": {
                "enabled": "${{ inputs.allow-snapshots }}",
                "updatePolicy": "never"
              }
            },
            {
              "id": "kogito-staging-repository-group",
              "name": "Kogito Staging Repositories",
              "url": "https://repository.jboss.org/nexus/content/groups/kogito-public",
              "releases": {
                "enabled": "true",
                "updatePolicy": "never"
              },
              "snapshots": {
                "enabled": "${{ inputs.allow-snapshots }}",
                "updatePolicy": "never"
              }
            }
          ]
        plugin_repositories: >
          [
            {
              "id": "jboss-public-repository-group",
              "name": "JBoss Public Repository Group",
              "url": "https://repository.jboss.org/nexus/content/groups/public",
              "releases": {
                "enabled": "true",
                "updatePolicy": "never"
              },
              "snapshots": {
                "enabled": "${{ inputs.allow-snapshots }}",
                "updatePolicy": "never"
              }
            },
            {
              "id": "kogito-staging-repository-group",
              "name": "Kogito Staging Repositories",
              "url": "https://repository.jboss.org/nexus/content/groups/kogito-public",
              "releases": {
                "enabled": "true",
                "updatePolicy": "never"
              },
              "snapshots": {
                "enabled": "${{ inputs.allow-snapshots }}",
                "updatePolicy": "never"
              }
            }
          ]
        plugin_groups: >
          [
            "org.zanata"
          ]
    - name: Debug settings.xml
      shell: bash
      run: |
        cat ~/.m2/settings.xml
