version: "2.1"

dependencies: ./project-dependencies-quarkus.yaml

pre: |
  export BUILD_MVN_OPTS="${{ env.BUILD_MVN_OPTS }} -nsu -fae -e -Dhttp.keepAlive=false -Dmaven.wagon.http.pool=false -Dmaven.wagon.httpconnectionManager.ttlSeconds=120"
  echo "BUILD_MVN_OPTS=${{ env.BUILD_MVN_OPTS }}"
  export BUILD_MVN_OPTS_NATIVE="-Pnative -Dquarkus.native.container-build=true -Dquarkus.native.container-runtime=docker -Dquarkus.profile=native"
  echo "BUILD_MVN_OPTS_NATIVE=${{ env.BUILD_MVN_OPTS_NATIVE }}"

default:
  build-command:
    current: mvn -e clean install ${{ env.BUILD_MVN_OPTS }}
    upstream: mvn -e clean install -DskipTests -Dquickly ${{ env.BUILD_MVN_OPTS }}
    after:
      current: |
        docker system prune -f

build:
  - project: kiegroup/kogito-runtimes
    build-command:
      current: |
        mvn -f kogito-runtimes/pom.xml clean install -Dvalidate-formatting ${{ env.BUILD_MVN_OPTS }}
    clone:
      - kogito-runtimes

  - project: kiegroup/optaplanner
    build-command: 
      current: mvn -f optaplanner/pom.xml clean install -Dfull ${{ env.BUILD_MVN_OPTS }} ${{ env.BUILD_MVN_OPTS_NATIVE }} 
    clone:
      - optaplanner

  - project: kiegroup/optaplanner-quickstarts
    build-command: 
      current: mvn clean install -Dfull ${{ env.BUILD_MVN_OPTS }} ${{ env.BUILD_MVN_OPTS_NATIVE }} 

  - project: kiegroup/kogito-apps
    build-command: 
      current: |
        mvn -f kogito-apps/pom.xml clean install -Dvalidate-formatting ${{ env.BUILD_MVN_OPTS }}
    clone:
      - kogito-apps

  - project: kiegroup/kogito-examples
    build-command: 
      current: |
        mvn -f kogito-examples/pom.xml clean install -Dvalidate-formatting ${{ env.BUILD_MVN_OPTS }}
        mvn -f kogito-examples-persistence/pom.xml clean install -Ppersistence ${{ env.BUILD_MVN_OPTS }}
        mvn -f kogito-examples-events/pom.xml clean install -Pevents ${{ env.BUILD_MVN_OPTS }}
    clone:
      - kogito-examples
      - kogito-examples-persistence
      - kogito-examples-events

  - project: kiegroup/quarkus
    build-command:
      upstream: mvn -e clean install -fae -Pjava.net.preferIPv4Stack=true -Pquickly -Dmaven.wagon.httpconnectionManager.ttlSeconds=25 -Dmaven.wagon.http.retryHandler.count=3
