ecosystem:
  main_project: kogito
  dependencies:
  - name: drools
  projects:
  - name: kogito
    default_main_version: 2.0.0-SNAPSHOT
    regexs:
    - kogito.*
    - incubator-kie-kogito.*
  # - name: kie-tools
  #   ignore_release: true
  #   regexs:
  #   - kie-tools.*
  #   - incubator-kie-tools.*
  - name: kie-docs
    ignore_release: true
    regexs:
    - kie-docs.*
    - incubator-kie-docs.*
git:
  branches:
  - name: main
    main_branch: true
seed:
  config_file:
    git:
      repository: incubator-kie-kogito-pipelines
      author:
        name: apache
        credentials_id: ASF_Cloudbees_Jenkins_ci-builds
        push:
          credentials_id: 84811880-2025-45b6-a44c-2f33bef30ad2 # CI Push Access for KIE
      branch: main
    path: .ci/jenkins/config/branch.yaml
  jenkinsfile: dsl/seed/jenkinsfiles/Jenkinsfile.seed.branch
jenkins:
  email_creds_id: KOGITO_CI_NOTIFICATION_EMAILS
