ecosystem:
  main_project: kogito
  dependencies:
  - name: drools
  projects:
  - name: kogito
    default_main_version: 2.0.0-SNAPSHOT
    regexs:
    - kogito.*
  - name: kie-tools
    ignore_release: true
    ignore_productization: true
    regexs:
    - kie-tools.*
  - name: kie-docs
    ignore_release: true
    ignore_productization: true
    regexs:
    - kie-docs.*
git:
  branches:
  - name: apache-test-config
    main_branch: true
seed:
  config_file:
    git:
      repository: kogito-pipelines
      author:
        name: radtriste
        credentials_id: radtriste
      branch: apache-test-config
    path: .ci/jenkins/config/branch.yaml
  jenkinsfile: dsl/seed/jenkinsfiles/Jenkinsfile.seed.branch
jenkins:
  email_creds_id: KOGITO_CI_EMAIL_TO_PERSO
