ecosystem:
  main_project: kogito
  dependencies:
  - name: drools
  projects:
  - name: kogito
    default_main_version: 2.0.0-SNAPSHOT
    regexs:
    - kogito.*
  # - name: kie-tools
  #   ignore_release: true
  #   regexs:
  #   - kie-tools.*
  - name: kie-docs
    ignore_release: true
    regexs:
    - kie-docs.*
git:
  branches:
  - name: apache_migration
    main_branch: true
seed:
  config_file:
    git:
      repository: kogito-pipelines
      author:
        name: kiegroup
        credentials_id: kie-ci3
      branch: apache_migration
    path: .ci/jenkins/config/branch.yaml
  jenkinsfile: dsl/seed/jenkinsfiles/Jenkinsfile.seed.branch
jenkins:
  email_creds_id: KOGITO_CI_NOTIFICATION_EMAILS
