ecosystem:
  main_project: kogito
  dependencies:
  - name: drools
  projects:
  - name: kogito
    default_main_version: 2.0.0-SNAPSHOT
    regexs:
    - kogito.*
    - incubator-kie-kogito.*
  - name: kie-docs
    ignore_release: true
    regexs:
    - kie-docs.*
    - incubator-kie-docs.*
git:
  branches:
  - name: main
    main_branch: true
seed:
  config_file:
    git:
      repository: incubator-kie-kogito-pipelines
      author:
        name: apache
        credentials_id: ASF_Cloudbees_Jenkins_ci-builds
        push:
          credentials_id: 84811880-2025-45b6-a44c-2f33bef30ad2
      branch: main
    path: .ci/jenkins/config/branch.yaml
  jenkinsfile: dsl/seed/jenkinsfiles/Jenkinsfile.seed.branch
jenkins:
  email_creds_id: KOGITO_CI_NOTIFICATION_EMAILS
  agent:
    docker:
      builder:
        # At some point, this image will need to be changed when a release branch is created
        # but we need to make sure the image exists first ... simple tag before setting up the branch ?
        # See https://github.com/kiegroup/kie-issues/issues/551
        image: quay.io/kiegroup/kogito-ci-build:main-latest
        args: --privileged --group-add docker
