environment:
  quarkus:
    main:
      enabled: false
    branch:
      enabled: true
      version: '2.7'
    lts:
      enabled: false
      version: '2.7'
  native:
    enabled: false
  mandrel:
    enabled: true
    builder_image: quay.io/quarkus/ubi-quarkus-mandrel:21.3-java11
  runtimes_bdd:
    enabled: true
productized_branch: true
disable:
  triggers: false
repositories:
- name: kogito-pipelines
  branch: 1.27.x
  is_branch_config_repo: true
- name: drools
  branch: 8.27.x
- name: kogito-runtimes
  branch: 1.27.x
- name: kogito-apps
  branch: 1.27.x
- name: kogito-examples
  branch: 1.27.x
- name: kogito-images
  branch: 1.27.x
- name: kogito-operator
  branch: 1.27.x
- name: kogito-docs
  branch: 1.27.x
git:
  author:
    name: kiegroup
    credentials_id: kie-ci
    token_credentials_id: kie-ci3-token
  bot_author:
    name: bsig-gh-bot
    credentials_id: bsig-gh-bot
  jenkins_config_path: .ci/jenkins
maven:
  settings_file_id: kogito_release_settings
  nexus:
    release_url: https://repository.jboss.org/nexus
    release_repository: jboss-releases-repository
    staging_profile_url: https://repository.jboss.org/nexus/content/groups/kogito-public/
    staging_profile_id: 1976dd1c18392a
    build_promotion_profile_id: ea49ccd6f174
  artifacts_repository: ''
  pr_checks:
    repository:
      url: https://bxms-qe.rhev-ci-vms.eng.rdu2.redhat.com:8443/nexus/content/repositories/kogito-runtimes-pr-full-testing/
      creds_id: unpacks-zip-on-qa-nexus
cloud:
  image:
    registry_credentials_nightly: nightly_kogito
    registry_credentials_release: release_kogito
    registry: quay.io
    namespace: kiegroup
    latest_git_branch: main
jenkins:
  email_creds_id: KOGITO_CI_EMAIL_TO
  default_tools:
    jdk: kie-jdk11
    maven: kie-maven-3.8.6
