environment:
  quarkus:
    main:
      enabled: true
    branch:
      enabled: true
      version: '2.14'
    lts:
      enabled: true
      version: '2.13'
  native:
    enabled: true
  mandrel:
    enabled: true
    builder_image: quay.io/quarkus/ubi-quarkus-mandrel:22.3-java17
  mandrel_lts:
    enabled: true
    builder_image: quay.io/quarkus/ubi-quarkus-mandrel:22.3-java17
    quarkus_version: 2.13
  runtimes_bdd:
    enabled: true
productized_branch: true
disable:
  triggers: false
repositories:
- name: kogito-pipelines
- name: drools
- name: drools-website
- name: kogito-runtimes
- name: kogito-apps
- name: kogito-examples
- name: kogito-images
- name: kogito-operator
- name: kogito-serverless-operator
- name: kie-tools
- name: kogito-docs
git:
  author:
    name: kiegroup
    credentials_id: kie-ci
    token_credentials_id: kie-ci3-token
  bot_author:
    name: bsig-gh-bot
    credentials_id: bsig-gh-bot
  fork_author:
    name: kie-ci
    credentials_id: kie-ci
  quarkus:
    author:
      name: quarkusio
      credentials_id: kie-ci
    branch: main
  jenkins_config_path: .ci/jenkins
buildchain_config:
  git:
    repository: kogito-pipelines
maven:
  settings_file_id: kogito_release_settings
  nexus:
    release_url: https://repository.jboss.org/nexus
    release_repository: jboss-releases-repository
    staging_profile_url: https://repository.jboss.org/nexus/content/groups/kogito-public/
    staging_profile_id: 1976dd1c18392a
    build_promotion_profile_id: ea49ccd6f174
  artifacts_repository: ''
  artifacts_upload_repository:
    url: https://repository.jboss.org/nexus/content/repositories/snapshots/
    creds_id: kie-ci1-upload
  pr_checks:
    repository:
      url: https://bxms-qe.rhev-ci-vms.eng.rdu2.redhat.com:8443/nexus/content/repositories/kogito-runtimes-pr-full-testing/
      creds_id: unpacks-zip-on-qa-nexus
cloud:
  image:
    registry_credentials_nightly: nightly_kogito
    registry_credentials_release: release_kogito
    registry: quay.io
    namespace: kiegroup
    latest_git_branch: main
jenkins:
  email_creds_id: KOGITO_CI_EMAIL_TO
  default_tools:
    jdk: kie-jdk11
    maven: kie-maven-3.8.6
