environment:
  quarkus:
    main:
      enabled: true
    branch:
      enabled: true
      version: '2.12'
    lts:
      enabled: true
      version: '2.7'
  native:
    enabled: true
  mandrel:
    enabled: true
    builder_image: quay.io/quarkus/ubi-quarkus-mandrel:22.2-java11
  runtimes_bdd:
    enabled: true
productized_branch: true
disable:
  triggers: true

repositories:
  - name: kogito-pipelines
    branch: test-pr
  - name: drools
    branch: main
  - name: kogito-runtimes
    branch: main
  - name: kogito-apps
    branch: main
  - name: kogito-examples
    branch: main
  - name: kogito-images
    branch: main
  - name: kogito-operator
    branch: main
  - name: kie-tools
    branch: main
  - name: kogito-docs
    branch: main

git:
  author:
    name: radtriste
    credentials_id: radtriste
    token_credentials_id: radtriste-gh-token
  bot_author:
    name: radtriste-bot-account
    credentials_id: radtriste-bot
  jenkins_config_path: .ci/jenkins
maven:
  settings_file_id: 2bd418aa-56fa-4403-9232-8c77a50fc528
  nexus:
    release_url: https://repository.stage.jboss.org/nexus
    release_repository: jboss-releases-repository
    staging_profile_url: https://repository.stage.jboss.org/nexus/content/groups/kogito-public/
    staging_profile_id: 2161b7b8da0080
    build_promotion_profile_id: 1966c60aff37d
  artifacts_repository: http://nexus3-tradisso-nexus.apps.kogito-cloud.hosted.psi.rdu2.redhat.com/repository/kogito-test/
  #artifacts_repository: ''
  pr_checks:
    repository:
      url: https://bxms-qe.rhev-ci-vms.eng.rdu2.redhat.com:8443/nexus/content/repositories/kogito-runtimes-pr-full-testing/
      creds_id: unpacks-zip-on-qa-nexus
cloud:
  image:
    registry_credentials_nightly: tradisso_registry_token
    registry_credentials_release: tradisso_registry_token
    registry: quay.io
    namespace: tradisso
    latest_git_branch: main
jenkins:
  email_creds_id: KOGITO_CI_EMAIL_TO_PERSO
  default_tools:
    jdk: kie-jdk11
    maven: kie-maven-3.8.6
