ecosystem:
  main_project: kogito
  projects:
  - name: drools
    regexs:
    - drools.*
  - name: kogito
    default_main_version: 2.0.0-SNAPSHOT
    regexs:
    - kogito.*
  - name: kie-tools
    ignore_release: true
    regexs:
    - kie-tools.*
git:
  branches:
  - name: main
    main_branch: true
    seed:
      branch: main
  - name: 1.13.x
    old_folder_structure: true
    seed:
      branch: 1.13.x
      config_file:
        path: dsl/seed/config/branch.yaml
      jenkinsfile: dsl/seed/jobs/Jenkinsfile.seed.branch
  - name: 1.13.x-blue
    old_folder_structure: true
    seed:
      branch: 1.13.x-blue
      config_file:
        path: dsl/seed/config/branch.yaml
      jenkinsfile: dsl/seed/jobs/Jenkinsfile.seed.branch
  - name: 1.29.x
    seed:
      branch: seed-kogito-1.29.x
  - name: 1.30.x
    seed:
      branch: seed-kogito-1.30.x
  - name: 1.31.x
    seed:
      branch: seed-kogito-1.31.x
  - name: 1.32.x
    seed:
      branch: seed-kogito-1.32.x
  main_branch:
    default: main
seed:
  config_file:
    git:
      repository: kogito-pipelines
      author:
        name: kiegroup
        credentials_id: kie-ci
      branch: main
    path: dsl/config/branch.yaml
  jenkinsfile: dsl/seed/jenkinsfiles/Jenkinsfile.seed.branch
jenkins:
  email_creds_id: KOGITO_CI_EMAIL_TO
