ecosystem:
  main_project: kogito
  projects:
  - name: drools
    regexs:
    - drools.*
  - name: kogito
    regexs:
    - kogito.*
  - name: kie-tools
    ignore_release: true
    regexs:
    - kie-tools.*
git:
  branches:
  - name: main
  - name: 1.11.x
    old_folder_structure: true
    seed:
      config_file:
        path: dsl/seed/config/branch.yaml
      jenkinsfile: dsl/seed/jobs/Jenkinsfile.seed.branch
  - name: 1.13.x
    old_folder_structure: true
    seed:
      config_file:
        path: dsl/seed/config/branch.yaml
      jenkinsfile: dsl/seed/jobs/Jenkinsfile.seed.branch
  - name: 1.13.x-blue
    old_folder_structure: true
    seed:
      config_file:
        path: dsl/seed/config/branch.yaml
      jenkinsfile: dsl/seed/jobs/Jenkinsfile.seed.branch
  - name: 1.22.x
    seed:
      config_file:
        path: dsl/seed/config/branch.yaml
      jenkinsfile: dsl/seed/jobs/Jenkinsfile.seed.branch
  - name: 1.23.x
    seed:
      config_file:
        path: dsl/seed/config/branch.yaml
      jenkinsfile: dsl/seed/jobs/Jenkinsfile.seed.branch
  - name: 1.24.x
    seed:
      config_file:
        git:
          branch: kogito-1.24.x
  main_branch:
    default: main
seed:
  config_file:
    git:
      repository: kogito-pipelines
      author:
        name: kiegroup
        credentials_id: kie-ci
      branch: main
    path: dsl/config/branch.yaml
  jenkinsfile: dsl/seed/jenkinsfiles/Jenkinsfile.seed.branch
jenkins:
  email_creds_id: KOGITO_CI_EMAIL_TO
