ecosystem:
  main_project: kogito
  dependencies:
  - name: drools
  projects:
  - name: kogito
    default_main_version: 2.0.0-SNAPSHOT
    regexs:
    - kogito.*
  - name: kie-tools
    ignore_release: true
    ignore_productization: true
    regexs:
    - kie-tools.*
  - name: kie-docs
    ignore_release: true
    ignore_productization: true
    regexs:
    - kie-docs.*
git:
  branches:
  - name: main
    main_branch: true
    seed:
      branch: main
  - name: 1.13.x
    old_folder_structure: true
    seed:
      branch: 1.13.x
      config_file:
        path: dsl/seed/config/branch.yaml
      jenkinsfile: dsl/seed/jobs/Jenkinsfile.seed.branch
  - name: 1.13.x-blue
    old_folder_structure: true
    seed:
      branch: 1.13.x-blue
      config_file:
        path: dsl/seed/config/branch.yaml
      jenkinsfile: dsl/seed/jobs/Jenkinsfile.seed.branch
  - name: 1.33.x
    seed:
      branch: seed-kogito-1.33.x
  - name: 1.35.x
    seed:
      branch: seed-kogito-1.35.x
  - name: 1.36.x
    seed:
      branch: seed-kogito-1.36.x
  - name: 1.37.x
    seed:
      branch: seed-kogito-1.37.x
  - name: 1.38.x
    seed:
      branch: seed-kogito-1.38.x
  - name: 1.38.x-prod
    seed:
      branch: seed-kogito-1.38.x
  - name: 1.39.x
    seed:
      branch: seed-kogito-1.39.x
seed:
  config_file:
    git:
      repository: kogito-pipelines
      author:
        name: kiegroup
        credentials_id: kie-ci3
      branch: main
    path: dsl/config/branch.yaml
  jenkinsfile: dsl/seed/jenkinsfiles/Jenkinsfile.seed.branch
jenkins:
  email_creds_id: KOGITO_CI_EMAIL_TO
