ecosystem:
  main_project: kogito
  projects:
  - name: drools
    regexs:
    - drools.*
  - name: kogito
    regexs:
    - kogito.*
  - name: kie-tools
    ignore_release: true
    regexs:
    - kie-tools.*
git:
  branches:
  - name: k6959
  main_branch:
    default: main
seed:
  config_file:
    git:
      repository: kogito-pipelines
      author:
        name: radtriste
        credentials_id: radtriste
      branch: k6959
    path: dsl/config/branch.yaml
  jenkinsfile: dsl/seed/jenkinsfiles/Jenkinsfile.seed.branch
jenkins:
  email_creds_id: KOGITO_CI_EMAIL_TO_PERSO
