name: 'Build Chain'
description: 'Executes build-chain tool'
inputs:
  github-token:
    description: "the github token"
    required: true
  definition-file:
    description: 'The `definition-file` input for the build-chain'
    required: false
    default: 'https://raw.githubusercontent.com/${GROUP:apache}/incubator-kie-kogito-pipelines/${BRANCH:main}/.ci/pull-request-config.yaml'
  flow-type:
    description: "the flow to execute, it can be 'cross_pr' (or 'pull-request' which is deprecated), 'full_downstream' (or 'full-downstream' which is deprecated), 'single_pr' (or 'single' which is deprecated) or 'branch'"
    default: "cross_pr"
    required: false
  starting-project:
    description: "the project to start flow from. By default is the project triggering the job"
    required: false
  logger-level:
    description: "the log level. 'info' (default) | 'trace' | 'debug'"
    default: "info"
    required: false
  annotations-prefix:
    description: "The prefix for the annotations title"
    default: ''
    required: false
  additional-flags:
    description: "The chance to define additional flags for the execution, as it is done on the CLI side. Just semicolon (;) separated, like '--skipParallelCheckout;--skipExecution;-cct (mvn .*)||$1 -s settings.xml'"
    required: false


runs:
  using: "composite"
  steps:
    - name: Setup nodejs
      id: setup-node
      uses: actions/setup-node@v4
      with:
        node-version: 16
    - run: |
        npm install -g @kie/build-chain-action@v3.5.5
        REPO_NAME=${{ github.event.pull_request.base.repo.full_name }}
        INPUT_STARTING_PROJECT=${{ inputs.starting-project }}
        if [[ -z "$INPUT_STARTING_PROJECT" ]]; then
          INPUT_STARTING_PROJECT=$REPO_NAME
        fi
        build-chain build ${{ inputs.flow-type }} \
          --token ${{ inputs.github-token }} \
          -f ${{ inputs.definition-file }} \
          -p $INPUT_STARTING_PROJECT \
          -u ${{ github.event.pull_request.html_url}} \
          -o ${{ env.GITHUB_WORKSPACE }} \
          ${{ inputs.additional-flags }} \
          --skipParallelCheckout
      shell: bash

