repositories:
  - name: kogito-pipelines
  - name: kogito-runtimes
  - name: kogito-apps
  - name: optaplanner
    jenkins_config_path: .ci/jenkins
  - name: kogito-examples
  - name: kogito-images
  - name: kogito-operator
  - name: rhpam-kogito-operator

# Full Example
# repositories:
#   - name: NAME
#     branch: branch_name
#     author:
#       name: another_gh_author
#       credentials_id: another_gh_author_creds
#       token_credentials_id: another_gh_author_creds_token
#     bot_author:
#       name: another_gh_bot_author
#       credentials_id: another_gh_bot_author_creds
#     jenkins_config_path: .jenkins/

# Main branch configuration
git:
  author:
    name: kiegroup
    credentials_id: kie-ci
    token_credentials_id: kie-ci2-token
  bot_author:
    name: bsig-gh-bot
    credentials_id: bsig-gh-bot
  jenkins_config_path: .jenkins
maven:
  settings_file_id: kogito_release_settings
  nexus:
    release_url: https://repository.jboss.org/nexus
    release_repository: jboss-releases-repository
    staging_profile_url: https://repository.jboss.org/nexus/content/groups/kogito-public/
    staging_profile_id: 2161b7b8da0080
    build_promotion_profile_id: ea49ccd6f174
  artifacts_repository: ''
  pr_checks:
    repository:
      url: https://bxms-qe.rhev-ci-vms.eng.rdu2.redhat.com:8443/nexus/content/repositories/kogito-runtimes-pr-full-testing/
      creds_id: unpacks-zip-on-qa-nexus
cloud:
  image:
    registry_credentials_nightly: nightly_kogito
    registry_credentials_release: release_kogito
    registry: quay.io
    namespace: kiegroup
    latest_git_branch: master
jenkins:
  email_creds_id: KOGITO_CI_EMAIL_TO
quarkus:
  lts_version: '1.11'
disable:
  triggers: false
  branch: false
