lts:
  enabled: true
  quarkus_version: '2.6'
  native_builder_image: quay.io/quarkus/ubi-quarkus-mandrel:21.3-java11
disable:
  triggers: false
  branch: false
repositories:
- name: kogito-pipelines
  branch: 1.16.x
- name: drools
  branch: 8.16.x
- name: kogito-runtimes
  branch: 1.16.x
- name: kogito-apps
  branch: 1.16.x
- name: kogito-examples
  branch: 1.16.x
- name: kogito-images
  branch: 1.16.x
- name: kogito-operator
  branch: 1.16.x
- name: optaplanner
  branch: 8.16.x
- name: optaweb-vehicle-routing
  branch: 8.16.x
- name: optaweb-employee-rostering
  branch: 8.16.x
- name: optaplanner-quickstarts
  branch: 8.16.x
git:
  author:
    name: kiegroup
    credentials_id: kie-ci
    token_credentials_id: kie-ci2-token
  bot_author:
    name: bsig-gh-bot
    credentials_id: bsig-gh-bot
  jenkins_config_path: .ci/jenkins
maven:
  settings_file_id: kogito_release_settings
  nexus:
    release_url: https://repository.jboss.org/nexus
    release_repository: jboss-releases-repository
    staging_profile_url: https://repository.jboss.org/nexus/content/groups/kogito-public/
    staging_profile_id: 2161b7b8da0080
    build_promotion_profile_id: ea49ccd6f174
  artifacts_repository: ''
  pr_checks:
    repository:
      url: https://bxms-qe.rhev-ci-vms.eng.rdu2.redhat.com:8443/nexus/content/repositories/kogito-runtimes-pr-full-testing/
      creds_id: unpacks-zip-on-qa-nexus
cloud:
  image:
    registry_credentials_nightly: nightly_kogito
    registry_credentials_release: release_kogito
    registry: quay.io
    namespace: kiegroup
    latest_git_branch: main
jenkins:
  email_creds_id: KOGITO_CI_EMAIL_TO
