# Disabled until Quarkus 2.2 is out
# Follow-up issue: https://issues.redhat.com/browse/KOGITO-5487
lts:
  enabled: true
  quarkus_version: '2.7'
  native_builder_image: quay.io/quarkus/ubi-quarkus-mandrel:21.3-java11

disable:
  triggers: true
  branch: false

repositories:
  - name: kogito-pipelines
  # - name: drools
  # - name: kogito-runtimes
  # - name: optaplanner
  # - name: optaweb-employee-rostering
  # - name: optaweb-vehicle-routing
  # - name: optaplanner-quickstarts
  - name: kogito-apps
  - name: kogito-examples
  # - name: kogito-images
  # - name: kogito-operator
  # - name: kie-tools

# Full Example
# repositories:
#   - name: NAME
#     branch: branch_name
#     disabled: false
#     author:
#       name: another_gh_author
#       credentials_id: another_gh_author_creds
#       token_credentials_id: another_gh_author_creds_token
#     bot_author:
#       name: another_gh_bot_author
#       credentials_id: another_gh_bot_author_creds
#     jenkins_config_path: .ci/jenkins/

# Main branch configuration
git:
  author:
    name: kiegroup
    credentials_id: radtriste
    token_credentials_id: radtriste-gh-token
  bot_author:
    name: radtriste-bot-account
    credentials_id: radtriste-bot
  jenkins_config_path: .ci/jenkins
maven:
  settings_file_id: 2bd418aa-56fa-4403-9232-8c77a50fc528
  nexus:
    release_url: https://repository.stage.jboss.org/nexus
    release_repository: jboss-releases-repository
    staging_profile_url: https://repository.stage.jboss.org/nexus/content/groups/kogito-public/
    staging_profile_id: 2161b7b8da0080
    build_promotion_profile_id: 1966c60aff37d
  artifacts_repository: http://nexus3-tradisso-nexus.apps.kogito-cloud.hosted.psi.rdu2.redhat.com/repository/kogito-test/
  #artifacts_repository: ''
  pr_checks:
    repository:
      url: https://bxms-qe.rhev-ci-vms.eng.rdu2.redhat.com:8443/nexus/content/repositories/kogito-runtimes-pr-full-testing/
      creds_id: unpacks-zip-on-qa-nexus
cloud:
  image:
    registry_credentials_nightly: tradisso_registry_token
    registry_credentials_release: tradisso_registry_token
    registry: quay.io
    namespace: tradisso
    latest_git_branch: main
jenkins:
  email_creds_id: KOGITO_CI_EMAIL_TO_PERSO
