name: Generate status page


on: workflow_dispatch

jobs:
  generate-status-page:
    if: github.repository_owner == 'apache'
    concurrency:
      group: generate-status-page
      cancel-in-progress: true
    runs-on: ubuntu-latest
    name: Generate status page
    steps:
      - name: Generate status page
        uses: kiegroup/chain-status/.ci/actions/generate-app@main
        with:
          info-md-url: "https://raw.githubusercontent.com/apache/kogito-pipelines/main/.ci/chain-status-info.md"
          github-token: "${{ secrets.GITHUB_TOKEN }}"
