# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Jenkins DSL

on:
  pull_request:
    paths:
    - 'dsl/**'

jobs:  
  downstream-dsl-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        repository:
        - drools
        - kogito-runtimes
        - optaplanner
        - optaweb-employee-rostering
        - optaweb-vehicle-routing
        - optaplanner-quickstarts
        - kogito-apps
        - kogito-examples
        - kogito-images
        - kogito-operator
        - kie-tools
      fail-fast: false
    name: Downstream - ${{ matrix.repository }}
    steps:
    - name: Checkout 
      uses: actions/checkout@v2

    - name: Set up JDK 1.11
      uses: actions/setup-java@v1
      with:
        java-version: 11

    - name: Test DSL
      run: cd .ci/jenkins/dsl && ./test.sh -r ${{ matrix.repository }} -b ${{ github.head_ref }} -o ${{ github.event.pull_request.user.login }} -t ${{ github.base_ref }} -a ${{ github.event.pull_request.base.user.login }} .ci/jenkins/dsl