# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Jenkins

on:
  pull_request:
    paths: 
    - '.ci/jenkins/**'
    - '.ci/actions/dsl-tests/**'
    - '.github/workflows/jenkins-tests.yml'
    - 'dsl/**'

jobs:
  jenkinsfile-tests:
    concurrency:
      group: ${{ github.repository.name }}-jenkinsfile_tests-${{ github.head_ref }}
      cancel-in-progress: true
    runs-on: ubuntu-latest
    name: Jenkinsfiles
    steps:
    - name: Checkout 
      uses: actions/checkout@v3
      with:
        path: main

    - name: Checkout shared libraries
      uses: actions/checkout@v3
      with:
        repository: kiegroup/jenkins-pipeline-shared-libraries
        path: shared-libs

    - name: Set up JDK 1.8
      uses: actions/setup-java@v3
      with:
        java-version: 11
        distribution: temurin
        check-latest: true

    - name: Test pipelines
      run: cd $GITHUB_WORKSPACE/main/.ci/jenkins/tests && mvn -B clean test

  dsl-tests:
    concurrency:
      group: ${{ github.repository.name }}-dsl_tests-${{ github.head_ref }}
      cancel-in-progress: true
    runs-on: ubuntu-latest
    steps:
    - name: DSL tests
      uses: kiegroup/kie-ci/.ci/actions/dsl-tests@main
      with:
        main-config-file-repo: kiegroup/kie-ci
        main-config-file-path: dsl/config/main.yaml
        branch-config-file-repo: kiegroup/kie-ci
        